Michael at Yosemite-Retina in ~/Desktop/info290/project/code/analysis on master*
$ python3 bayes.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pandas/io/pickle.py", line 45, in try_read
    with open(path, 'rb') as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'processed/pandas/American_IPA.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pandas/io/pickle.py", line 51, in try_read
    with open(path, 'rb') as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'processed/pandas/American_IPA.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pandas/io/pickle.py", line 60, in read_pickle
    return try_read(path)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pandas/io/pickle.py", line 56, in try_read
    with open(path, 'rb') as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'processed/pandas/American_IPA.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pandas/io/pickle.py", line 45, in try_read
    with open(path, 'rb') as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'processed/pandas/American_IPA.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pandas/io/pickle.py", line 51, in try_read
    with open(path, 'rb') as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'processed/pandas/American_IPA.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bayes.py", line 49, in <module>
    data = read_pickle("processed/pandas/%s.pkl"%(STYLE))
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pandas/io/pickle.py", line 63, in read_pickle
    return try_read(path, encoding='latin1')
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pandas/io/pickle.py", line 56, in try_read
    with open(path, 'rb') as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'processed/pandas/American_IPA.pkl'
Michael at Yosemite-Retina in ~/Desktop/info290/project/code/analysis on master*
$ cd ..
Michael at Yosemite-Retina in ~/Desktop/info290/project/code on master*
$ cd ..
Michael at Yosemite-Retina in ~/Desktop/info290/project on master*
$ python3 code/analysis/bayes.py
Basic Logistic Regression
0.484224186876
Traceback (most recent call last):
  File "code/analysis/bayes.py", line 75, in <module>
    clf = GridSearchCV(LogisticRegression(penalty='l2'), param_grid)
NameError: name 'LogisticRegression' is not defined
Michael at Yosemite-Retina in ~/Desktop/info290/project on master*
$ python3 -i code/analysis/bayes.py
Gaussian NB
0.484224186876
Multinomial NB
0.515775813124
>>> cross_val(data, labels, 10, 2, mnb)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'mnb' is not defined
>>> cross_val(data, labels, 10, 2, mbn)